import Head from "next/head";
import PrimaryAppBar from "../common/Home/Navbar";
import { ReactNode } from "react";
import { Box } from "@mui/material";
import Sidebar from "../common/Home/Sidebar";

interface Homeinterface {
  children: ReactNode;
}

const drawerWidth = 360;

export default function Dashboard({ children }: Homeinterface) {
  return (
    <>
      <Head>
        <title>devGeni</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          backgroundColor: "#D9D9D9",
          minHeight: "100vh"
        }}
      >
        <Box>
          <PrimaryAppBar />
          <Box sx={{ display: "flex" }}>
            <Sidebar />
            <Box
              sx={{
                width: { md: `calc(100% - ${drawerWidth}px)` },
                pl: 1,
                '@media(max-width:768px)':{ padding:"0 20px"}
              }}
            >
              <main>{children}</main>
            </Box>
          </Box>
        </Box>
      </Box>
    </>
  );
}
