import { Box, IconButton, useTheme } from "@mui/material";
import Head from "next/head";
import ProjectSummary from "../../common/Dashboard/DashboardContent/ProjectSummary";
import NavbarPage from "../../components/Home/NavbarPage";
import LandingPage from "../../components/Home/LandingPage";
import PartnersPage from "../../components/Home/PartnersPage";
import ProjectsPage from "../../components/Home/ProjectsPage";
import AboutDevgeni from "../../components/Home/AboutDevgeniPage";
import ServicesPage from "../../components/Home/ServicePage";
import BuildPage from "../../components/Home/BuildPage";
import { createTheme } from "@mui/material/styles";
import React from "react";
import { ThemeProvider } from "@emotion/react";
import { Brightness4, Brightness7 } from "@mui/icons-material";
import FooterPage from "../../components/Home/FooterPage";
import SkillPage from "../../components/Home/SkillPage";

const ColorModeContext = React.createContext({ toggleColorMode: () => {} });

function MyApp() {
  const theme = useTheme();
  const colorMode = React.useContext(ColorModeContext);
  return (
    <Box
      sx={{
        display: "flex",
        width: "100%",
        alignItems: "center",
        justifyContent: "center",
        bgcolor: "background.default",
        color: "text.primary",
        borderRadius: 1,
        p: 3,
      }}
    >
      {theme.palette.mode} mode
      <IconButton
        sx={{ ml: 1 }}
        onClick={colorMode.toggleColorMode}
        color="inherit"
      >
        {theme.palette.mode === "dark" ? <Brightness7 /> : <Brightness4 />}
      </IconButton>
    </Box>
  );
}

export default function Home() {
  const [mode, setMode] = React.useState<"light" | "dark">("light");
  const colorMode = React.useMemo(
    () => ({
      toggleColorMode: () => {
        setMode((prevMode) => (prevMode === "light" ? "dark" : "light"));
      },
    }),
    []
  );

  const theme = React.useMemo(
    () =>
      createTheme({
        palette: {
          mode,
        },
      }),
    [mode]
  );

  return (
    <>
      <Head>
        <title>devGeni App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ColorModeContext.Provider value={colorMode}>
        <ThemeProvider theme={theme}>
          <Box sx={{ background: "#000F08" }}>
            <NavbarPage />
            <LandingPage />
            <PartnersPage />
            <ProjectsPage />
            <AboutDevgeni />
            <ServicesPage />
            <BuildPage />
            <SkillPage />
            <FooterPage />
          </Box>
        </ThemeProvider>
      </ColorModeContext.Provider>
    </>
  );
}
