import { Box } from "@mui/material";
import Head from "next/head";
import SignIn from "../../components/auth/signUp";
import ProjectSummary from "../../common/Home/DashboardContent/ProjectSummary";

export default function Home() {
  return (
    <>
      <Head>
        <title>devGeni App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <SignIn />
      </Box>
    </>
  );
}
